--- makefile.orig	2023-11-09 00:38:43.684378523 -0800
+++ makefile	2023-11-09 00:38:59.076326295 -0800
@@ -1,6 +1,6 @@
-
-EXES = qbsp light vis bspinfo entmap visx
-NTEXES = qbsp.exe light.exe vis.exe bspinfo.exe entmap.exe visx.exe
+CFLAGS = -I ../common -Wno-implicit-function-declaration
+EXES = qbsp light vis bspinfo
+NTEXES = qbsp.exe light.exe vis.exe bspinfo.exe
 
 #==============================================================================
 
@@ -39,27 +39,28 @@
          merge$(EXT) outside$(EXT) portals$(EXT) qbsp$(EXT) solidbsp$(EXT) tjunc$(EXT)\
          writebsp$(EXT) bspfile$(EXT) nodraw$(EXT)
 qbsp : $(QBSPFILES)
-	$(CC) $(CFLAGS) -o qbsp $(QBSPFILES)
+	$(CC) $(CFLAGS) -o qbsp $(QBSPFILES) -lm
+
+light : ../light/threads$(EXT) bspfile$(EXT) cmdlib$(EXT) ../light/light$(EXT) ../light/ltface$(EXT) mathlib$(EXT) ../light/trace$(EXT) ../light/entities$(EXT)
+	$(CC) $(CFLAGS) -o light ../light/threads$(EXT) bspfile$(EXT) cmdlib$(EXT) ../light/light$(EXT) ../light/ltface$(EXT) mathlib$(EXT) ../light/trace$(EXT) ../light/entities$(EXT) -lm
 
-light : threads$(EXT) bspfile$(EXT) cmdlib$(EXT) light$(EXT) ltface$(EXT) mathlib$(EXT) trace$(EXT) entities$(EXT)
-	$(CC) $(CFLAGS) -o light threads$(EXT) bspfile$(EXT) cmdlib$(EXT) light$(EXT) ltface$(EXT) mathlib$(EXT) trace$(EXT) entities$(EXT)
-	
-vis : vis$(EXT) flow$(EXT) cmdlib$(EXT) mathlib$(EXT) bspfile$(EXT) soundpvs$(EXT)
-	$(CC) $(CFLAGS) -o vis vis$(EXT) flow$(EXT) cmdlib$(EXT) mathlib$(EXT) bspfile$(EXT) soundpvs$(EXT)
+vis : ../vis/vis$(EXT) ../vis/flow$(EXT) cmdlib$(EXT) mathlib$(EXT) bspfile$(EXT) ../vis/soundpvs$(EXT)
+	$(CC) $(CFLAGS) -o vis ../vis/vis$(EXT) ../vis/flow$(EXT) cmdlib$(EXT) mathlib$(EXT) bspfile$(EXT) ../vis/soundpvs$(EXT) -lm
 
 visx : visx$(EXT) flowx$(EXT) cmdlib$(EXT) mathlib$(EXT) bspfile$(EXT) soundpvs$(EXT)
 	$(CC) $(CFLAGS) -o visx visx$(EXT) flowx$(EXT) cmdlib$(EXT) mathlib$(EXT) bspfile$(EXT) soundpvs$(EXT)
 
-bspinfo : bspinfo$(EXT) bspfile$(EXT) cmdlib$(EXT)
-	$(CC) $(CFLAGS) -o bspinfo bspinfo$(EXT) bspfile$(EXT) cmdlib$(EXT)
+bspinfo : ../bspinfo/bspinfo$(EXT) bspfile$(EXT) cmdlib$(EXT)
+	$(CC) $(CFLAGS) -o bspinfo ../bspinfo/bspinfo$(EXT) bspfile$(EXT) cmdlib$(EXT) -lm
 
 entmap : entmap$(EXT) cmdlib$(EXT)
 	$(CC) $(CFLAGS) -o entmap entmap$(EXT) cmdlib$(EXT)
 
 
-cmdlib$(EXT) : ../cmdlib.c
-	$(CC) $(CFLAGS) -c -o cmdlib$(EXT) ../cmdlib.c
-mathlib$(EXT) : ../mathlib.c
-	$(CC) $(CFLAGS) -c -o mathlib$(EXT) ../mathlib.c
-
+cmdlib$(EXT) : ../common/cmdlib.c
+	$(CC) $(CFLAGS) -c -o cmdlib$(EXT) ../common/cmdlib.c
+mathlib$(EXT) : ../common/mathlib.c
+	$(CC) $(CFLAGS) -c -o mathlib$(EXT) ../common/mathlib.c -lm
+bspfile$(EXT) : ../common/bspfile.c
+	$(CC) $(CFLAGS) -c -o bspfile$(EXT) ../common/bspfile.c
 
